[package]
name = "samfuslib"
version = "0.1.0"
authors = ["Andrew Gunnerson <chillermillerlong@hotmail.com>"]
edition = "2018"

[dependencies]
aes-soft = "0.6.4"
base64 = "0.13.0"
block-modes = "0.7.0"
block-padding = "0.2.1"
bytes = "1.0.0"
cfg-if = "1.0.0"
cipher = "0.2.5"
futures-core = "0.3.8"
hex-literal = "0.3.1"
log = "0.4.11"
md5 = "0.7.0"
reqwest = { version = "0.11.0", features = ["cookies", "stream"] }
thiserror = "1.0.23"
xmltree = "0.10.2"

[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))'.dependencies]
aesni = { version = "0.10.0", features = ["nocheck"] }

[dev-dependencies]
assert_matches = "1.4.0"
