[package]
name = "samfuslib"
version = "0.1.2"
authors = ["Andrew Gunnerson <chillermillerlong@hotmail.com>"]
edition = "2018"

[dependencies]
aes = "0.7.5"
base64 = "0.13.0"
block-modes = "0.8.1"
block-padding = "0.2.1"
bytes = "1.0.0"
cipher = "0.3.0"
futures-core = "0.3.8"
hex-literal = "0.3.1"
log = "0.4.11"
md5 = "0.7.0"
reqwest = { version = "0.11.0", features = ["cookies", "stream"] }
thiserror = "1.0.23"
xmltree = "0.10.2"

[dev-dependencies]
assert_matches = "1.4.0"
