[package]
name = "samfusdl"
version = "0.1.1"
authors = ["Andrew Gunnerson <chillermillerlong@hotmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.37"
clap = "3.0.0-beta.4"
crc32fast = "1.2.1"
dirs = "4.0.0"
env_logger = "0.9.0"
futures = "0.3.8"
futures-util = "0.3.8"
log = "0.4.11"
progresslib = { path = "progresslib" }
samfuslib = { path = "samfuslib" }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
tokio = { version = "1.0.1", features = ["full"] }
tokio-stream = "0.1.1"

[target.'cfg(windows)'.dependencies]
memoffset = "0.6.1"
winapi = "0.3.9"

[workspace]
members = ["progresslib", "samfuslib"]
