[package]
name = "samfusdl"
version = "0.1.0"
authors = ["Andrew Gunnerson <chillermillerlong@hotmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
clap = "3.0.0-beta.2"
crc32fast = "1.2.0"
dirs = "3.0.1"
env_logger = "0.7.1"
futures = "0.3.5"
futures-util = "0.3.5"
log = "0.4.11"
progresslib = { path = "progresslib" }
samfuslib = { path = "samfuslib" }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
tokio = { version = "0.2.22", features = ["full"] }

[target.'cfg(windows)'.dependencies]
memoffset = "0.5.6"
winapi = "0.3.9"

[workspace]
members = ["progresslib", "samfuslib"]
