[package]
name = "samfusdl"
version = "0.1.3"
authors = ["Andrew Gunnerson <chillermillerlong@hotmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.52"
clap = { version = "3.0.0", features = ["derive", "env"] }
crc32fast = "1.3.0"
dirs = "4.0.0"
env_logger = "0.9.0"
futures = "0.3.19"
futures-util = "0.3.19"
log = "0.4.14"
progresslib = { path = "progresslib" }
samfuslib = { path = "samfuslib" }
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
tokio = { version = "1.15.0", features = ["full"] }
tokio-stream = "0.1.8"

[target.'cfg(windows)'.dependencies]
memoffset = "0.6.5"
winapi = "0.3.9"

[workspace]
members = ["progresslib", "samfuslib"]
