---
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build_and_upload:
    name: Build and archive artifacts
    runs-on: ${{ matrix.os }}
    env:
      CARGO_TERM_COLOR: always
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get Rust LLVM target triple
        id: get_target
        shell: bash
        run: |
          echo -n '::set-output name=name::'
          RUSTC_BOOTSTRAP=1 rustc -Z unstable-options --print target-spec-json \
              | jq -r '."llvm-target"'

      - name: Run tests in debug mode
        env:
          RUST_BACKTRACE: 1
          # ENABLE_VIRTUAL_TERMINAL_PROCESSING does not work in GitHub Actions,
          # so set TERM to force crossterm to output ANSI sequences.
          TERM: xterm
        run: cargo test --workspace

      - name: Build in debug mode
        run: cargo build --verbose

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: samfusdl-${{ steps.get_target.outputs.name }}
          path: |
            target/debug/samfusdl.exe
            target/debug/samfusdl.pdb
            target/debug/samfusdl
